# bpo-issues-41654
Showcase for https://bugs.python.org/issue41654
